version: "3.7"
services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - redis
  # nginx:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend